import os
import json
import subprocess
from flask import Blueprint, render_template, jsonify
from CTFd.utils.decorators import admins_only
from CTFd.plugins import register_plugin_assets_directory

def load_plugin(app):
    # 1. Define the Blueprint
    reachability_bp = Blueprint('reachability', __name__, template_folder='templates')

    @reachability_bp.route('/admin/reachability', methods=['GET'])
    @admins_only
    def admin_view():
        """Renders the reachability dashboard."""
        return render_template('validate.html')

    @reachability_bp.route('/admin/reachability/check', methods=['POST'])
    @admins_only
    def check_connectivity():
        """Reads Terraform output and pings the target."""
        # Path to the JSON file generated by Terraform
        # In a Docker environment, ensure this path is volume-mapped
        tf_output_path = os.getenv('TF_OUTPUT_PATH', '/var/ctfd/tf_output.json')

        if not os.path.exists(tf_output_path):
            return jsonify({
                "success": False, 
                "message": f"Terraform output file not found at {tf_output_path}"
            }), 404

        try:
            with open(tf_output_path, 'r') as f:
                data = json.load(f)
                # Parse the target IP from Terraform's specific JSON structure
                target_ip = data.get('target_ip', {}).get('value')

            if not target_ip:
                return jsonify({"success": False, "message": "Target IP not found in JSON"}), 400

            # 2. Perform ICMP check (Ping)
            # -c 1 (1 packet), -W 2 (2 second timeout)
            process = subprocess.run(
                ["ping", "-c", "1", "-W", "2", target_ip],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE
            )

            if process.returncode == 0:
                return jsonify({
                    "success": True,
                    "status": "Online",
                    "ip": target_ip,
                    "message": f"Successfully reached {target_ip}"
                })
            else:
                return jsonify({
                    "success": False,
                    "status": "Offline",
                    "ip": target_ip,
                    "message": "Target is unreachable. Check Security Group rules."
                })

        except Exception as e:
            return jsonify({"success": False, "message": str(e)}), 500

    # 3. Register the Blueprint and Plugin
    app.register_blueprint(reachability_bp)